//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_Hermes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alumno()
        {
            this.AfiliacionSeguroAlumno = new HashSet<AfiliacionSeguroAlumno>();
        }
    
        public int ID { get; set; }
        public string ApellidoPaternno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> TipoDocumentoID { get; set; }
        public string NumeroDocumento { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string CodigoAlumno { get; set; }
        public string Carrera { get; set; }
        public Nullable<int> Sexo { get; set; }
        public Nullable<int> GradoID { get; set; }
        public string Seccion { get; set; }
        public Nullable<int> BeneficiarioID { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioActualizacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<int> asociacionid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AfiliacionSeguroAlumno> AfiliacionSeguroAlumno { get; set; }
        public virtual Grado Grado { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
    }
}
