//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_Hermes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asociacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Asociacion()
        {
            this.AsociacionDetalle = new HashSet<AsociacionDetalle>();
            this.CampaniaDetalle = new HashSet<CampaniaDetalle>();
            this.CargaHistorial = new HashSet<CargaHistorial>();
            this.Codigo = new HashSet<Codigo>();
        }
    
        public int ID { get; set; }
        public int InstitucionEducativaID { get; set; }
        public int CIASeguroID { get; set; }
        public int RecaudadorID { get; set; }
        public Nullable<int> MonedaID { get; set; }
        public int ProductoID { get; set; }
        public Nullable<bool> TipoPrima { get; set; }
        public byte[] FilePlanSeguro { get; set; }
        public decimal Prima { get; set; }
        public string NroPoliza { get; set; }
        public string CodigoContratante { get; set; }
        public string NombreContratante { get; set; }
        public Nullable<System.DateTime> FechaVigenciaInicio { get; set; }
        public Nullable<System.DateTime> FechaVigenciaFin { get; set; }
        public Nullable<System.DateTime> FechaVigenciaPolizaInicio { get; set; }
        public Nullable<System.DateTime> FechaVigenciaPolizaFin { get; set; }
        public Nullable<decimal> GastoCuracion { get; set; }
        public Nullable<decimal> InvalidezPermanenteTotal { get; set; }
        public Nullable<decimal> InvalidezPermanenteParcial { get; set; }
        public Nullable<decimal> MuerteAccidental { get; set; }
        public Nullable<decimal> GastosSepelio { get; set; }
        public Nullable<decimal> PensionMensual { get; set; }
        public Nullable<int> MesesPension { get; set; }
        public Nullable<int> AnniosPension { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioActualizacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string FileNamePlanSeguro { get; set; }
        public Nullable<int> TipoCargaCodigos { get; set; }
        public Nullable<int> TipoAsociacion { get; set; }
        public Nullable<decimal> Deducible { get; set; }
    
        public virtual CIASeguro CIASeguro { get; set; }
        public virtual CIASeguro CIASeguro1 { get; set; }
        public virtual InstitucionEducativa InstitucionEducativa { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Producto Producto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AsociacionDetalle> AsociacionDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaniaDetalle> CampaniaDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CargaHistorial> CargaHistorial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Codigo> Codigo { get; set; }
    }
}
