//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_Hermes
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaracterEspecial
    {
        public int ID { get; set; }
        public Nullable<int> CaracterEspecialTipoID { get; set; }
        public string Caracter { get; set; }
        public string Reemplazo { get; set; }
        public Nullable<bool> PermiteIngreso { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        public virtual CaracterEspecialTipo CaracterEspecialTipo { get; set; }
    }
}
