//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_Hermes
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargaTxtParametro
    {
        public int ID { get; set; }
        public int BancoID { get; set; }
        public int BancoParametroTipoID { get; set; }
        public int Orden { get; set; }
        public string NombreColumna { get; set; }
        public string DescripcionColumna { get; set; }
        public string PopertyName { get; set; }
        public string Valor { get; set; }
        public int Longitud { get; set; }
        public int PosicionStart { get; set; }
        public int PosicionEnd { get; set; }
        public bool IsMappingEntity { get; set; }
        public bool Actvo { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual BancoParametroTipo BancoParametroTipo { get; set; }
    }
}
