//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_Hermes
{
    using System;
    using System.Collections.Generic;
    using ViewModel;

    public partial class Cheque
    {
        public int ID { get; set; }
        public int CampaniaID { get; set; }
        public int InstitucionEducativaID { get; set; }
        public int CIASeguroID { get; set; }
        public int ProductoID { get; set; }
        public Nullable<int> BancoID { get; set; }
        public int MonedaID { get; set; }
        public System.DateTime Fecha { get; set; }
        public string NroCheque { get; set; }
        public decimal Monto { get; set; }
        public string Concepto { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioActualizacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public bool Activo { get; set; }

        public virtual Banco Banco { get; set; }
        public virtual CIASeguro CIASeguro { get; set; }
        public virtual InstitucionEducativa InstitucionEducativa { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Campania Campania { get; set; }

        public List<Bancos> listBanco;
        public List<Cia_Seguro> listCIASeguro;
        public List<Institucion_Educativa> listInstitucionEducativa;
        public List<Moneda> listMoneda;
        public List<Producto> listProducto;
        public List<Campañas> listCampañas;

        public Cheque()
        {
            listBanco = new List<Bancos>();
            listCIASeguro = new List<Cia_Seguro>();
            listInstitucionEducativa = new List<Institucion_Educativa>();
            listMoneda = new List<Moneda>();
            listProducto = new List<Producto>();
            listCampañas = new List<Campañas>();

        }
    }
}
