//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_Hermes
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodigoDetallePago
    {
        public int ID { get; set; }
        public int CodigoDetalleID { get; set; }
        public System.DateTime FechaPago { get; set; }
        public string OperacionBancaria { get; set; }
        public int MonedaPagoID { get; set; }
        public int BancoPagoID { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual CodigoDetalle CodigoDetalle { get; set; }
    }
}
