//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_Hermes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Codigo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Codigo()
        {
            this.CodigoDetalle = new HashSet<CodigoDetalle>();
        }
    
        public int ID { get; set; }
        public int AsociacionID { get; set; }
        public int InstitucionEducativaID { get; set; }
        public int ProductoID { get; set; }
        public int CIASeguroID { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Descripcion { get; set; }
        public string UsuarioCreacion { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public string UsuarioActualizacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    
        public virtual CIASeguro CIASeguro { get; set; }
        public virtual InstitucionEducativa InstitucionEducativa { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Asociacion Asociacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CodigoDetalle> CodigoDetalle { get; set; }
    }
}
