//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_Hermes
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodigoDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CodigoDetalle()
        {
            this.CodigoDetallePago = new HashSet<CodigoDetallePago>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CodigoID { get; set; }
        public Nullable<int> CargaHistorialID { get; set; }
        public Nullable<int> ProductoID { get; set; }
        public Nullable<int> AfiliacionSeguroID { get; set; }
        public Nullable<int> AfiliacionSeguroAlumnoID { get; set; }
        public Nullable<int> AfiliacionSeguroPadreID { get; set; }
        public Nullable<int> Correlativo { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<bool> RecibidoBanco { get; set; }
        public Nullable<bool> TipoCarga { get; set; }
        public string Observacion { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public string OperacionBancaria { get; set; }
        public Nullable<int> MonedaPagoID { get; set; }
        public Nullable<int> BancoPagoID { get; set; }
        public Nullable<bool> IsPagado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioActualizacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public bool Activo { get; set; }
        public string UsuarioAfiliacion { get; set; }
    
        public virtual AfiliacionSeguro AfiliacionSeguro { get; set; }
        public virtual AfiliacionSeguroAlumno AfiliacionSeguroAlumno { get; set; }
        public virtual AfiliacionSeguroPadre AfiliacionSeguroPadre { get; set; }
        public virtual Banco Banco { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Codigo Codigo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CodigoDetallePago> CodigoDetallePago { get; set; }
    }
}
