//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_Hermes
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracionArchivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConfiguracionArchivo()
        {
            this.CIASeguroProducto = new HashSet<CIASeguroProducto>();
            this.ConfiguracionArchivoDetalle = new HashSet<ConfiguracionArchivoDetalle>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ConfiguracionArchivoTipoID { get; set; }
        public Nullable<int> CIASeguroID { get; set; }
        public Nullable<int> ProductoID { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioActualizacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CIASeguroProducto> CIASeguroProducto { get; set; }
        public virtual ConfiguracionArchivoTipo ConfiguracionArchivoTipo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfiguracionArchivoDetalle> ConfiguracionArchivoDetalle { get; set; }
    }
}
