//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_Hermes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contacto
    {
        public int ID { get; set; }
        public Nullable<int> BancoID { get; set; }
        public Nullable<int> InstitucionEducativaID { get; set; }
        public string Nombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Email { get; set; }
        public string Cargo { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioActualizado { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual InstitucionEducativa InstitucionEducativa { get; set; }
    }
}
