//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_Hermes
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoCorreo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GrupoCorreo()
        {
            this.logPromoDet = new HashSet<logPromoDet>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> InstitucionEducativaID { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> origen { get; set; }
        public Nullable<System.DateTime> fe_reg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<logPromoDet> logPromoDet { get; set; }
    }
}
