//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_Hermes
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstitucionEducativa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InstitucionEducativa()
        {
            this.AfiliacionSeguro = new HashSet<AfiliacionSeguro>();
            this.Contacto = new HashSet<Contacto>();
            this.Asociacion = new HashSet<Asociacion>();
            this.Cheque = new HashSet<Cheque>();
            this.Codigo1 = new HashSet<Codigo>();
        }
    
        public int ID { get; set; }
        public Nullable<int> TipoInstitucionEducativaID { get; set; }
        public Nullable<int> TipoDocumentoID { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public string RazonSocial { get; set; }
        public Nullable<int> TipoEmpresa { get; set; }
        public string NumeroDocumento { get; set; }
        public string CodigoUbigeo { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string ApellidoPaternno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string NombreNatural { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioActualizacion { get; set; }
        public Nullable<System.DateTime> FechaActualizacion { get; set; }
        public Nullable<bool> Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AfiliacionSeguro> AfiliacionSeguro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contacto> Contacto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Asociacion> Asociacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cheque> Cheque { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Codigo> Codigo1 { get; set; }
        public virtual TipoDocumento TipoDocumento { get; set; }
        public virtual TipoInstitucionEducativa TipoInstitucionEducativa { get; set; }
    }
}
