//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_Hermes
{
    using System;
    using System.Collections.Generic;
    
    public partial class logPromoDet
    {
        public int ID { get; set; }
        public Nullable<int> logPromoID { get; set; }
        public Nullable<int> id_grupo_correo { get; set; }
        public string destinatario { get; set; }
    
        public virtual GrupoCorreo GrupoCorreo { get; set; }
        public virtual logPromo logPromo { get; set; }
    }
}
