//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_Hermes
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonaPreg
    {
        public int Id { get; set; }
        public int PersonaTipoId { get; set; }
        public int PersonaId { get; set; }
        public Nullable<int> PreguntaId { get; set; }
        public string Rspta { get; set; }
    }
}
