//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_Hermes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plantilla_Detalle
    {
        public int id { get; set; }
        public int id_plantilla { get; set; }
        public string NombreArchivoImagen { get; set; }
        public string ruta_imagen { get; set; }
        public int id_estado { get; set; }
        public System.DateTime fec_reg { get; set; }
        public string ruta_site_imagen { get; set; }
    
        public virtual Plantilla Plantilla { get; set; }
    }
}
