//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_Hermes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plantilla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plantilla()
        {
            this.logPromo = new HashSet<logPromo>();
            this.Plantilla_Detalle = new HashSet<Plantilla_Detalle>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public string NombreArchivoHtml { get; set; }
        public string ruta_plantilla_html { get; set; }
        public int id_estado { get; set; }
        public System.DateTime fec_reg { get; set; }
        public Nullable<int> fl_parrafo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<logPromo> logPromo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plantilla_Detalle> Plantilla_Detalle { get; set; }
    }
}
