//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO_Hermes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reg_Online
    {
        public int Id { get; set; }
        public string Padre_ApePaterno { get; set; }
        public string Padre_ApeMaterno { get; set; }
        public string Padre_Nombres { get; set; }
        public string Padre_FechaNacimiento { get; set; }
        public Nullable<int> Padre_TipoDocumento { get; set; }
        public string Padre_NumDocumento { get; set; }
        public Nullable<int> Padre_IdBeneficiario { get; set; }
        public Nullable<int> Padre_TipoPadre { get; set; }
        public string Bene_ApePaterno { get; set; }
        public string Bene_ApeMaterno { get; set; }
        public string Bene_ApeNombres { get; set; }
        public Nullable<int> Bene_TipoDocumento { get; set; }
        public string Bene_NumDocumento { get; set; }
        public string Bene_FechaNacimiento { get; set; }
        public string Bene_Grado { get; set; }
        public Nullable<int> Bene_Sexo { get; set; }
        public string Prima { get; set; }
        public string TipoSeguro { get; set; }
        public string CompañiaSeguro { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<int> ReservadoId { get; set; }
        public Nullable<int> MonedaId { get; set; }
        public string Colegio { get; set; }
        public Nullable<int> IdProducto { get; set; }
        public Nullable<int> IdAsociacion { get; set; }
        public Nullable<int> idInstitucionEducativa { get; set; }
        public string Bene_Seccion { get; set; }
        public Nullable<int> TipoRegistro { get; set; }
        public Nullable<int> ad1EstCivilId { get; set; }
        public string ad1NacPais { get; set; }
        public Nullable<int> ad1DirPaisId { get; set; }
        public string ad1DirDptCod { get; set; }
        public string ad1DirPrvCod { get; set; }
        public string ad1DirDisCod { get; set; }
        public string ad1DirEnt { get; set; }
        public string ad1TlfnoDom { get; set; }
        public string ad1TlfnoTrb { get; set; }
        public string ad1NroCel { get; set; }
        public string ad1DirMail { get; set; }
        public Nullable<int> ad1Sexo { get; set; }
        public string ad1Carrera { get; set; }
    }
}
